apiVersion: v1
kind: Secret

metadata:
  name: api-secret
  namespace: bank-complaint

type: Opaque

stringData:
  SQL_SERVER_PASSWORD: "CHANGE_ME"
  JWT_SECRET: "CHANGE_ME"
  ADMIN_PASSWORD: "CHANGE_ME"
