apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: sqlserver-pvc
  namespace: bank-complaint

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi

  storageClassName: standard
