apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring

data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:

      # Prometheus lui-même
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090

      # Kube-State-Metrics
      - job_name: kube-state-metrics
        static_configs:
          - targets:
              - kube-state-metrics.monitoring.svc.cluster.local:8080

      # Kubernetes Pods
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - bank-complaint

        relabel_configs:

          # Scraper uniquement les Pods annotés
          - source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scrape
            action: keep
            regex: true

          # Utiliser le port indiqué dans l'annotation
          - source_labels:
              - __address__
              - __meta_kubernetes_pod_annotation_prometheus_io_port
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__

          # Utiliser le chemin indiqué dans l'annotation
          - source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_path
            action: replace
            target_label: __metrics_path__
            regex: (.+)
