apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring

data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:

      # Prometheus lui-même
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090

      # Kube-State-Metrics
      - job_name: kube-state-metrics
        static_configs:
          - targets:
              - kube-state-metrics.monitoring.svc.cluster.local:8080

      # Kubernetes Pods
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - bank-complaint

        relabel_configs:

          # Scraper uniquement les Pods annotés
          - source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scrape
            action: keep
            regex: true

          # Utiliser le port indiqué dans l'annotation
          - source_labels:
              - __address__
              - __meta_kubernetes_pod_annotation_prometheus_io_port
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__

          # Utiliser le chemin indiqué dans l'annotation
          - source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_path
            action: replace
            target_label: __metrics_path__
            regex: (.+)

          # Conserver les informations Kubernetes
          - source_labels:
              - __meta_kubernetes_namespace
            action: replace
            target_label: namespace

          - source_labels:
              - __meta_kubernetes_pod_name
            action: replace
            target_label: pod

          - source_labels:
              - __meta_kubernetes_pod_container_name
            action: replace
            target_label: container

          # Récupérer le label Kubernetes app
          - source_labels:
              - __meta_kubernetes_pod_label_app
            action: replace
            target_label: app

      # Node Exporter - métriques des nœuds Kubernetes
      - job_name: node-exporter
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - monitoring

        relabel_configs:

          # Scraper uniquement les Pods Node Exporter
          - source_labels:
              - __meta_kubernetes_pod_label_app
            action: keep
            regex: node-exporter

          # Utiliser automatiquement le port 9100
          - source_labels:
              - __address__
            action: replace
            regex: ([^:]+)(?::\d+)?
            replacement: $1:9100
            target_label: __address__

          # Ajouter le nom du nœud Kubernetes
          - source_labels:
              - __meta_kubernetes_pod_node_name
            action: replace
            target_label: node
