apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  namespace: monitoring
  labels:
    app: alloy

spec:
  selector:
    matchLabels:
      app: alloy

  template:
    metadata:
      labels:
        app: alloy

    spec:
      serviceAccountName: alloy

      containers:
        - name: alloy
          image: grafana/alloy:v1.11.0

          args:
            - run
            - /etc/alloy/config.alloy
            - --server.http.listen-addr=0.0.0.0:12345

          ports:
            - name: http
              containerPort: 12345

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi

          volumeMounts:
            - name: config
              mountPath: /etc/alloy

            - name: containers
              mountPath: /var/log/containers
              readOnly: true

            - name: pods
              mountPath: /var/log/pods
              readOnly: true

            - name: positions
              mountPath: /tmp/alloy

      volumes:
        - name: config
          configMap:
            name: alloy-config

        - name: containers
          hostPath:
            path: /var/log/containers

        - name: pods
          hostPath:
            path: /var/log/pods

        - name: positions
          hostPath:
            path: /var/lib/alloy
            type: DirectoryOrCreate
