apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank-complaint-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    repoURL: https://github.com/fida-ghourabi/bank-complaint-management-infra.git
    targetRevision: main
    path: k8s/ingress

  destination:
    server: https://kubernetes.default.svc
    namespace: bank-complaint

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
