apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-namespace
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    repoURL: https://github.com/fida-ghourabi/bank-complaint-management-infra.git
    targetRevision: main
    path: k8s/monitoring/namespace

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
